- name: Deploy
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.SERVER_IP }}
    username: ${{ secrets.DEPLOY_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    source: "./"
    target: "/var/www/chentaomm.cn/html/"
